### PR TITLE
Add confetti

### PR DESCRIPTION
**Pull request by Tanmay41**
Hi! @ankitkat042 ,
I added the confetti celebration in your project "ThalaForAReason" as listed in README.md

you can also change the emojies or text used in confetti in the function which is trigred on THALAFORAREASON!!!!!!!!!

### CODE REVIEW

**Comment by Tanmay41** [comment]
@ankitkat042

**Comment by Tanmay41** [comment]
@ankitkat042

**Comment by ankitkat042** [comment]
thanks for this feature, I'll review it soon

**Comment by ankitkat042** [comment]
thanks!

**Pull request merged**
